# Generated by Django 5.0.1 on 2024-01-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('categories', models.CharField(max_length=150)),
            ],
        ),
    ]
