# Generated by Django 5.0.1 on 2024-01-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
